proxy:
  http: socks5://127.0.0.1:7897 # null
  https: socks5://127.0.0.1:7897
max_threads: 2
headful: 0
main_driver_headless: False
header:
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/118.0.0.0 Safari/537.36
save: "/mnt/data/Project/twitter_user_tweet_crawler/save"
user: plantgazer
click: |
  let element = document.querySelector('div[data-testid="cellInnerDiv"]:nth-of-type(1) div[class*="tmd-down"]');
  element.addEventListener('click', () => hasClickEvent = true);
  element.dispatchEvent(new Event('click'));